### PR TITLE
Add embedCSS option

### PR DESCRIPTION
**Pull request by Arkitecht**
Add embedCSS option (default true) to allow the option to be passed in,
to prevent embedding CSS in the head when this is not desired.

usage:
$('#select').ddslick({
embedCSS: false
});

### CODE REVIEW

**Comment by prashantchaudhary** [comment]
So just curious why would one want to disable CSS, do you see a case where a user would want to completely add a new CSS of his or her own. I can think a need of overriding few styles but there are css positioning that plugin uses and shouldn't be missed.

**Comment by Arkitecht** [comment]
It allows for more flexibility in the plugin, and some developers may find this more convenient than having to "undo" any unwanted styling available in the embedded CSS. In my experience, I had predefined styles for a similar tool already defined, and it was easier for me to start with nothing, and apply these styles, than to override the embedded ones.

**Comment by localpcguy** [comment]
It definitely would allow for more flexibility and developers will often want or need to use their own CSS.  I would, rather than adding an option to remove the embedded CSS, add the CSS via a separate style sheet that the developer who uses the plugin can use as is or modify as needed.  That would also strip a few bytes out of the JS.  (And a smart dev will just add the CSS to one of their existing CSS files, or concatenate it during the build process, so no need to worry about additional HTTP requests for the file.)

**Comment by prashantchaudhary** [comment]
A few users have been hitting me with the same request on my blog as well. Seems like the 'embedCSS' option will be a good addition! Also since it doesn't alter the default functionality of the plugin, I'm going to go ahead and merge the pull request by @ArkITechT

**Pull request merged**
